In [2]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
ckp_path = './metadata/DINOv2_checkpoint/'

In [13]:
eval_dirs = ('Symmetry_ue_train', 'ProteinClass_ue_train', 'MolecularWeight_kDa_ue_train',
             'ImagePixelSize_ue_train', 'EMD_Resolution_ue_train',  'DefocusV_ue_train')

# Create DataFrame with explicit column
df1 = pd.DataFrame(index=sorted(eval_dirs), columns=['value'])

for d in eval_dirs:
    csv_path = os.path.join(ckp_path, f'Linear_{d}', 'results-linear.csv')
    
    if os.path.exists(csv_path):
        try:
            df1.loc[d, 'value'] = pd.read_csv(csv_path).iloc[0, 0]
        except (ValueError, IndexError):
            df1.loc[d, 'value'] = 0.0
    else:
        df1.loc[d, 'value'] = 0.0

# Convert to numeric (in case of mixed types)
df1['value'] = pd.to_numeric(df1['value'])

# Add mean row
df1.loc['mean'] = df1.mean()

In [14]:
df1

                                  value
DefocusV_ue_train             79.470003
EMD_Resolution_ue_train       96.844643
ImagePixelSize_ue_train       98.667902
MolecularWeight_kDa_ue_train  98.022795
ProteinClass_ue_train         97.816253
Symmetry_ue_train             99.010855
mean                          94.972075

In [15]:
eval_dirs = ('Symmetry_ue_train_on_eval', 'ProteinClass_ue_train_on_eval', 'MolecularWeight_kDa_ue_train_on_eval',
             'ImagePixelSize_ue_train_on_eval', 'EMD_Resolution_ue_train_on_eval',  'DefocusV_ue_train_on_eval')

# Create DataFrame with explicit column
df2 = pd.DataFrame(index=sorted(eval_dirs), columns=['value'])

for d in eval_dirs:
    csv_path = os.path.join(ckp_path, f'Linear_{d}', 'results-linear.csv')
    
    if os.path.exists(csv_path):
        try:
            df2.loc[d, 'value'] = pd.read_csv(csv_path).iloc[0, 0]
        except (ValueError, IndexError):
            df2.loc[d, 'value'] = 0.0
    else:
        df2.loc[d, 'value'] = 0.0

# Convert to numeric (in case of mixed types)
df2['value'] = pd.to_numeric(df2['value'])

# Add mean row
df2.loc['mean'] = df2.mean()

In [16]:
df2

                                          value
DefocusV_ue_train_on_eval             57.699376
EMD_Resolution_ue_train_on_eval       35.808334
ImagePixelSize_ue_train_on_eval       47.025657
MolecularWeight_kDa_ue_train_on_eval  22.724999
ProteinClass_ue_train_on_eval         35.940278
Symmetry_ue_train_on_eval             41.459376
mean                                  40.109670

In [22]:
ln_accuracy = np.load(f'{ckp_path}linear_accuracy_per_eval_empiar.npy')
ln_accuracy = ln_accuracy.astype(object)
ln_accuracy = np.where(ln_accuracy == '', np.nan, ln_accuracy)
ln_accuracy[:,:,1] = ln_accuracy[:,:,1].astype(float)
tasksf = ('Symmetry', 'Function', 'Molecular_Weight',
          'Image_Pixel_Size', 'EMDB_Resolution', 'Defocus')
accuracy_dict = {tasksf[i]:ia for i, ia in enumerate(ln_accuracy)}